name: stacked_cards        # lowercase, underscores
description: A Flutter widget that shows animated, tappable stacked cards.
version: 1.1.0+1  # The version number is a string that follows the
# semantic versioning: MAJOR.MINOR.PATCH

homepage: https://github.com/Sunilnani/stacked_card
repository: https://github.com/Sunilnani/stacked_card
license: MIT

environment:
  sdk: ">=2.18.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/screenshot.jpeg
    - assets/demo.gif
    - assets/demo.mp4
